//! Differential AXON Schema 2026 conformance against the fixture generated by
//! `gen_schema.py` from the Python reference implementation.

use core::cmp::Ordering;

use serde_axon::parser::{Limits, Options};
use serde_axon::regex::safe_regex_search;
use serde_axon::schema::{
    PathSegment, SCHEMA_DIALECT_2026, SchemaError, SchemaErrorKind, SchemaRegistry2026,
    ValidationIssue, ValidationOptions, ValidationReport, normalize_schema, normalize_schema_with,
    validation_report2026_with,
};
use serde_axon::{Value, from_str_stream_with, writer};
use serde_json::Value as Json;

const DEFAULT_MAX_MODULES: usize = 1_024;
const DEFAULT_MAX_DEPTH: usize = 128;
const DEFAULT_MAX_NODES: usize = 1_048_576;
const DEFAULT_MAX_ISSUES: usize = 256;

fn fixture() -> Json {
    serde_json::from_str(include_str!("schema.json")).expect("schema.json parses")
}

fn options_for(profile: &str) -> Options {
    let base = Options {
        limits: Limits::default(),
        ..Options::default()
    };
    match profile {
        "core" => base,
        "doc_link" => Options {
            doc_link: true,
            ..base
        },
        "graph" => Options {
            graph: true,
            ..base
        },
        "scale_significant" => Options {
            scale_significant: true,
            ..base
        },
        other => panic!("unknown AXON profile in schema.json: {other}"),
    }
}

fn parse_one(source: &str, profile: &str) -> Value {
    let values = from_str_stream_with(source, options_for(profile)).unwrap_or_else(|error| {
        panic!("fixture AXON does not parse ({profile}): {source:?}: {error}")
    });
    assert_eq!(
        values.len(),
        1,
        "fixture AXON must contain exactly one value: {source:?}"
    );
    values.into_iter().next().unwrap()
}

fn canonical(value: &Value) -> String {
    writer::to_string_canonical(value).unwrap()
}

fn schema_error_kind(error: &SchemaError) -> &'static str {
    match error.kind {
        SchemaErrorKind::InvalidSchema => "value",
        SchemaErrorKind::ResourceLimit => "resource-limit",
        SchemaErrorKind::RegistryFrozen => "RuntimeError",
    }
}

fn expected_schema_error_kind(record: &Json) -> &'static str {
    match record["error_kind"].as_str().unwrap() {
        // Rust deliberately has one InvalidSchema variant where Python
        // distinguishes TypeError from ValueError.
        "type" | "value" => "value",
        "resource-limit" => "resource-limit",
        "RuntimeError" => "RuntimeError",
        other => panic!("unknown schema error kind in fixture: {other}"),
    }
}

fn path_from_json(path: &Json) -> Vec<PathSegment> {
    path.as_array()
        .unwrap()
        .iter()
        .map(|segment| {
            if let Some(index) = segment.as_u64() {
                PathSegment::Index(index as usize)
            } else if let Some(key) = segment.as_str() {
                PathSegment::Key(Value::String(key.to_owned()))
            } else {
                panic!("unsupported path segment in schema fixture: {segment}")
            }
        })
        .collect()
}

fn issue_from_json(issue: &Json) -> ValidationIssue {
    ValidationIssue {
        code: issue["code"].as_str().unwrap().to_owned(),
        path: path_from_json(&issue["path"]),
        message: issue["message"].as_str().unwrap().to_owned(),
        schema_path: path_from_json(&issue["schema_path"]),
    }
}

fn expected_report(record: &Json) -> ValidationReport {
    let issues = record["issues"]
        .as_array()
        .unwrap()
        .iter()
        .map(issue_from_json)
        .collect();
    let counts = record["counts"]
        .as_array()
        .unwrap()
        .iter()
        .map(|entry| {
            let pair = entry.as_array().unwrap();
            (
                pair[0].as_str().unwrap().to_owned(),
                pair[1].as_u64().unwrap() as usize,
            )
        })
        .collect();
    ValidationReport {
        issues,
        counts,
        truncated: record["truncated"].as_bool().unwrap(),
    }
}

fn report_differences(actual: &ValidationReport, expected: &Json) -> Vec<String> {
    let expected_report = expected_report(expected);
    let mut failures = Vec::new();
    if actual.valid() != expected["valid"].as_bool().unwrap() {
        failures.push(format!(
            "valid was {}, expected {}",
            actual.valid(),
            expected["valid"].as_bool().unwrap()
        ));
    }
    if actual.issues != expected_report.issues {
        failures.push(format!(
            "issues differed\n  got: {:#?}\n want: {:#?}",
            actual.issues, expected_report.issues
        ));
    }
    if actual.counts != expected_report.counts {
        failures.push(format!(
            "counts differed: got {:?}, want {:?}",
            actual.counts, expected_report.counts
        ));
    }
    if actual.truncated != expected_report.truncated {
        failures.push(format!(
            "truncated was {}, expected {}",
            actual.truncated, expected_report.truncated
        ));
    }
    failures
}

fn registry_with_config(config: &Json) -> Result<SchemaRegistry2026, SchemaError> {
    let max_modules = config
        .get("max_modules")
        .and_then(Json::as_u64)
        .map_or(DEFAULT_MAX_MODULES, |value| value as usize);
    let max_depth = config
        .get("max_depth")
        .and_then(Json::as_u64)
        .map_or(DEFAULT_MAX_DEPTH, |value| value as usize);
    let max_nodes = config
        .get("max_nodes")
        .and_then(Json::as_u64)
        .map_or(DEFAULT_MAX_NODES, |value| value as usize);
    SchemaRegistry2026::with_limits(max_modules, max_depth, max_nodes)
}

fn expected_modules(value: &Json) -> Vec<(String, String)> {
    value
        .as_array()
        .unwrap()
        .iter()
        .map(|entry| {
            let entry = entry.as_array().unwrap();
            (
                entry[0].as_str().unwrap().to_owned(),
                entry[1].as_str().unwrap().to_owned(),
            )
        })
        .collect()
}

fn canonical_modules(modules: Vec<(String, Value)>) -> Vec<(String, String)> {
    modules
        .into_iter()
        .map(|(identifier, schema)| (identifier, canonical(&schema)))
        .collect()
}

fn json_scalar_to_axon(value: &Json) -> Value {
    match value {
        Json::Null => Value::Null,
        Json::Bool(value) => Value::Bool(*value),
        Json::Number(value) => Value::Int(value.to_string()),
        Json::String(value) => Value::String(value.clone()),
        _ => panic!("registry mutation fixture must contain a scalar: {value}"),
    }
}

fn mutate_mapping(value: &mut Value, key: &str, replacement: &Json) -> bool {
    let pairs = match value {
        Value::Map(pairs) | Value::OrderedMap(pairs) => pairs,
        _ => return false,
    };
    let Some((_, value)) = pairs
        .iter_mut()
        .find(|(candidate, _)| matches!(candidate, Value::String(name) if name == key))
    else {
        return false;
    };
    *value = json_scalar_to_axon(replacement);
    true
}

#[test]
fn fixture_metadata_matches_public_dialect() {
    let data = fixture();
    assert_eq!(data["dialect"].as_str().unwrap(), SCHEMA_DIALECT_2026);
}

#[test]
fn safe_regex_matches_reference() {
    let data = fixture();
    let mut failures = Vec::new();

    for case in data["safe_regex"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let pattern = case["pattern"].as_str().unwrap();
        let value = case["value"].as_str().unwrap();
        match (
            case["outcome"].as_str().unwrap(),
            safe_regex_search(pattern, value),
        ) {
            ("match", Ok(true)) | ("no-match", Ok(false)) => {}
            ("match", Ok(false)) => failures.push(format!("{id}: expected match, got no match")),
            ("no-match", Ok(true)) => failures.push(format!("{id}: expected no match, got match")),
            (expected @ ("match" | "no-match"), Err(error)) => {
                failures.push(format!(
                    "{id}: expected {expected}, got error: {}",
                    error.message
                ));
            }
            ("error", Ok(matched)) => {
                failures.push(format!("{id}: expected error, got match result {matched}"));
            }
            ("error", Err(error)) => {
                if error.message != case["message"].as_str().unwrap() {
                    failures.push(format!(
                        "{id}: error message {:?}, expected {:?}",
                        error.message,
                        case["message"].as_str().unwrap()
                    ));
                }
                if error.message.is_empty() {
                    failures.push(format!("{id}: returned an empty error message"));
                }
            }
            (other, _) => panic!("unknown safe-regex outcome in fixture: {other}"),
        }
    }

    assert!(
        failures.is_empty(),
        "{} safe-regex mismatch(es):\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn schema_normalization_matches_reference() {
    let data = fixture();
    let mut failures = Vec::new();

    for case in data["normalization"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let profile = case.get("profile").and_then(Json::as_str).unwrap_or("core");
        let schema = parse_one(case["schema"].as_str().unwrap(), profile);
        let result = if case.get("max_depth").is_some() || case.get("max_nodes").is_some() {
            normalize_schema_with(
                &schema,
                case.get("max_depth")
                    .and_then(Json::as_u64)
                    .map_or(DEFAULT_MAX_DEPTH, |value| value as usize),
                case.get("max_nodes")
                    .and_then(Json::as_u64)
                    .map_or(DEFAULT_MAX_NODES, |value| value as usize),
            )
        } else {
            normalize_schema(&schema)
        };

        match (case["outcome"].as_str().unwrap(), result) {
            ("ok", Ok(normalized)) => {
                let got = canonical(&normalized);
                let want = case["normalized"].as_str().unwrap();
                if got != want {
                    failures.push(format!("{id}: normalized to {got:?}, expected {want:?}"));
                }
            }
            ("ok", Err(error)) => {
                failures.push(format!("{id}: expected success, got {error:?}"));
            }
            ("error", Ok(normalized)) => failures.push(format!(
                "{id}: expected error, normalized to {:?}",
                canonical(&normalized)
            )),
            ("error", Err(error)) => {
                let got_kind = schema_error_kind(&error);
                let want_kind = expected_schema_error_kind(case);
                if got_kind != want_kind {
                    failures.push(format!(
                        "{id}: error kind {got_kind:?}, expected {want_kind:?}"
                    ));
                }
                let want_message = case["message"].as_str().unwrap();
                if error.message != want_message {
                    failures.push(format!(
                        "{id}: error message {:?}, expected {want_message:?}",
                        error.message
                    ));
                }
            }
            (other, _) => panic!("unknown normalization outcome in fixture: {other}"),
        }
    }

    assert!(
        failures.is_empty(),
        "{} normalization mismatch(es):\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn registry_identifiers_and_config_match_reference() {
    let data = fixture();
    let registry = &data["registry"];
    let mut failures = Vec::new();

    for case in registry["identifiers"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let Some(identifier) = case["identifier"].as_str() else {
            // The Rust API accepts only &str, so Python's non-string dynamic
            // type error cannot be expressed at this boundary.
            continue;
        };
        match (
            case["outcome"].as_str().unwrap(),
            SchemaRegistry2026::validate_identifier(identifier),
        ) {
            ("ok", Ok(normalized)) => {
                if normalized != case["normalized"].as_str().unwrap() {
                    failures.push(format!(
                        "identifier {id}: normalized to {normalized:?}, expected {:?}",
                        case["normalized"].as_str().unwrap()
                    ));
                }
            }
            ("ok", Err(error)) => {
                failures.push(format!("identifier {id}: expected success, got {error:?}"));
            }
            ("error", Ok(normalized)) => failures.push(format!(
                "identifier {id}: expected error, accepted {normalized:?}"
            )),
            ("error", Err(error)) => {
                if schema_error_kind(&error) != expected_schema_error_kind(case) {
                    failures.push(format!(
                        "identifier {id}: wrong error kind {:?}",
                        error.kind
                    ));
                }
                if error.message != case["message"].as_str().unwrap() {
                    failures.push(format!(
                        "identifier {id}: error message {:?}, expected {:?}",
                        error.message,
                        case["message"].as_str().unwrap()
                    ));
                }
            }
            (other, _) => panic!("unknown identifier outcome in fixture: {other}"),
        }
    }

    for case in registry["config"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let config = &case["config"];
        if config
            .as_object()
            .unwrap()
            .values()
            .any(|value| value.as_u64().is_none())
        {
            // Non-integer constructor arguments are unrepresentable in Rust.
            continue;
        }
        match (
            case["outcome"].as_str().unwrap(),
            registry_with_config(config),
        ) {
            ("ok", Ok(registry)) => {
                if registry.frozen() != case["frozen"].as_bool().unwrap()
                    || registry.network_resolution()
                        != case["network_resolution"].as_bool().unwrap()
                    || registry.len() != case["length"].as_u64().unwrap() as usize
                {
                    failures.push(format!("config {id}: initial registry state differs"));
                }
            }
            ("ok", Err(error)) => {
                failures.push(format!("config {id}: expected success, got {error:?}"));
            }
            ("error", Ok(_)) => failures.push(format!("config {id}: expected error, accepted")),
            ("error", Err(error)) => {
                if schema_error_kind(&error) != expected_schema_error_kind(case) {
                    failures.push(format!("config {id}: wrong error kind {:?}", error.kind));
                }
                if error.message != case["message"].as_str().unwrap() {
                    failures.push(format!(
                        "config {id}: error message {:?}, expected {:?}",
                        error.message,
                        case["message"].as_str().unwrap()
                    ));
                }
            }
            (other, _) => panic!("unknown registry config outcome in fixture: {other}"),
        }
    }

    assert!(
        failures.is_empty(),
        "{} registry identifier/config mismatch(es):\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn validation_reports_match_reference() {
    let data = fixture();
    let mut failures = Vec::new();

    for case in data["validation"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let value = parse_one(
            case["value"].as_str().unwrap(),
            case["value_profile"].as_str().unwrap(),
        );
        let schema = parse_one(case["schema"].as_str().unwrap(), "core");
        let mut registry = SchemaRegistry2026::new();
        if let Some(modules) = case.get("registry") {
            for module in modules.as_array().unwrap() {
                let module_schema = parse_one(module["schema"].as_str().unwrap(), "core");
                registry
                    .register(module["identifier"].as_str().unwrap(), &module_schema)
                    .unwrap_or_else(|error| panic!("{id}: fixture registry failed: {error}"));
            }
        }
        let report = validation_report2026_with(
            &value,
            &schema,
            Some(&registry),
            ValidationOptions {
                max_depth: case
                    .get("max_depth")
                    .and_then(Json::as_u64)
                    .map_or(DEFAULT_MAX_DEPTH, |value| value as usize),
                max_issues: case
                    .get("max_issues")
                    .and_then(Json::as_u64)
                    .map_or(DEFAULT_MAX_ISSUES, |value| value as usize),
                scale_significant: case["value_profile"].as_str() == Some("scale_significant"),
            },
        );
        failures.extend(
            report_differences(&report, &case["report"])
                .into_iter()
                .map(|difference| format!("{id}: {difference}")),
        );
    }

    assert!(
        failures.is_empty(),
        "{} validation-report mismatch(es):\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn issue_ordering_fixture_preserves_typed_paths_and_uniqueness() {
    let data = fixture();
    let ordering = &data["issue_ordering"];
    let input: Vec<_> = ordering["input"]
        .as_array()
        .unwrap()
        .iter()
        .map(issue_from_json)
        .collect();
    let ordered: Vec<_> = ordering["ordered_unique"]
        .as_array()
        .unwrap()
        .iter()
        .map(issue_from_json)
        .collect();

    assert!(
        input.len() > ordered.len(),
        "fixture must exercise deduplication"
    );
    assert_eq!(
        ordered
            .iter()
            .filter(|issue| issue.code == "minimum")
            .count(),
        1,
        "duplicate issues must be removed"
    );
    assert!(matches!(
        ordered[1].path.as_slice(),
        [PathSegment::Index(1)]
    ));
    assert!(matches!(
        ordered[2].path.as_slice(),
        [PathSegment::Key(Value::String(value))] if value == "1"
    ));

    // The arbitrary-issue ordering helper is intentionally private. Every
    // public validation report is compared in the preceding test, including
    // stable path order, stable code order, deduplication, and issue limits.
    let mut sorted = input;
    sorted.sort_by(compare_reference_issues);
    sorted.dedup();
    assert_eq!(sorted, ordered);
}

fn compare_reference_issues(left: &ValidationIssue, right: &ValidationIssue) -> Ordering {
    compare_reference_path(&left.path, &right.path)
        .then_with(|| left.code.cmp(&right.code))
        .then_with(|| compare_reference_path(&left.schema_path, &right.schema_path))
        .then_with(|| left.message.cmp(&right.message))
}

fn compare_reference_path(left: &[PathSegment], right: &[PathSegment]) -> Ordering {
    for (left, right) in left.iter().zip(right) {
        let order = path_sort_key(left).cmp(&path_sort_key(right));
        if order != Ordering::Equal {
            return order;
        }
    }
    left.len().cmp(&right.len())
}

fn path_sort_key(segment: &PathSegment) -> (&'static str, String) {
    match segment {
        PathSegment::Index(index) => ("int", index.to_string()),
        PathSegment::Key(Value::String(value)) => ("str", format!("{value:?}")),
        PathSegment::Key(value) => ("Value", canonical(value)),
    }
}

#[test]
fn registry_scenarios_match_reference() {
    let data = fixture();
    let mut failures = Vec::new();

    for scenario in data["registry"]["scenarios"].as_array().unwrap() {
        let scenario_id = scenario["id"].as_str().unwrap();
        let empty_config = Json::Object(Default::default());
        let config = scenario.get("config").unwrap_or(&empty_config);
        let mut registry = registry_with_config(config)
            .unwrap_or_else(|error| panic!("{scenario_id}: invalid fixture config: {error}"));

        for (step_index, step) in scenario["steps"].as_array().unwrap().iter().enumerate() {
            let op = step["op"].as_str().unwrap();
            let expected = &step["result"];
            let label = format!("{scenario_id} step {step_index} ({op})");
            match op {
                "register" => {
                    let schema = parse_one(step["schema"].as_str().unwrap(), "core");
                    let result = registry.register_with(
                        step["identifier"].as_str().unwrap(),
                        &schema,
                        step.get("replace").and_then(Json::as_bool).unwrap_or(false),
                    );
                    match (expected["outcome"].as_str().unwrap(), result) {
                        ("ok", Ok(mut returned)) => {
                            let got = canonical(&returned);
                            let want = expected["schema"].as_str().unwrap();
                            if got != want {
                                failures
                                    .push(format!("{label}: returned {got:?}, expected {want:?}"));
                            }
                            if let Some(mutation) = step.get("mutate_return") {
                                for (key, replacement) in mutation.as_object().unwrap() {
                                    if !mutate_mapping(&mut returned, key, replacement) {
                                        failures.push(format!(
                                            "{label}: could not apply clone-isolation mutation {key:?}"
                                        ));
                                    }
                                }
                            }
                        }
                        ("ok", Err(error)) => {
                            failures.push(format!("{label}: expected success, got {error:?}"));
                        }
                        ("error", Ok(returned)) => failures.push(format!(
                            "{label}: expected error, returned {:?}",
                            canonical(&returned)
                        )),
                        ("error", Err(error)) => {
                            if schema_error_kind(&error) != expected_schema_error_kind(expected) {
                                failures.push(format!(
                                    "{label}: error kind {:?}, expected {:?}",
                                    error.kind,
                                    expected["error_kind"].as_str().unwrap()
                                ));
                            }
                            if error.message != expected["message"].as_str().unwrap() {
                                failures.push(format!(
                                    "{label}: error message {:?}, expected {:?}",
                                    error.message,
                                    expected["message"].as_str().unwrap()
                                ));
                            }
                        }
                        (other, _) => panic!("unknown registry step outcome: {other}"),
                    }
                }
                "get" => {
                    let Some(mut returned) = registry.get(step["identifier"].as_str().unwrap())
                    else {
                        failures.push(format!("{label}: registered module was absent"));
                        continue;
                    };
                    let got = canonical(&returned);
                    let want = expected["schema"].as_str().unwrap();
                    if got != want {
                        failures.push(format!("{label}: returned {got:?}, expected {want:?}"));
                    }
                    if let Some(mutation) = step.get("mutate_return") {
                        for (key, replacement) in mutation.as_object().unwrap() {
                            if !mutate_mapping(&mut returned, key, replacement) {
                                failures.push(format!(
                                    "{label}: could not apply clone-isolation mutation {key:?}"
                                ));
                            }
                        }
                    }
                }
                "snapshot" => {
                    let mut snapshot = registry.snapshot();
                    let got = canonical_modules(snapshot.clone());
                    let want = expected_modules(&expected["modules"]);
                    if got != want {
                        failures.push(format!("{label}: snapshot {got:?}, expected {want:?}"));
                    }
                    if let Some(mutation) = step.get("mutate_schema") {
                        let identifier = mutation["identifier"].as_str().unwrap();
                        let Some((_, schema)) = snapshot
                            .iter_mut()
                            .find(|(candidate, _)| candidate == identifier)
                        else {
                            failures.push(format!(
                                "{label}: snapshot mutation target {identifier:?} absent"
                            ));
                            continue;
                        };
                        if !mutate_mapping(
                            schema,
                            mutation["key"].as_str().unwrap(),
                            &mutation["value"],
                        ) {
                            failures.push(format!("{label}: could not mutate snapshot clone"));
                        }
                    }
                }
                "freeze" => {
                    registry.freeze();
                    if registry.frozen() != expected["frozen"].as_bool().unwrap() {
                        failures.push(format!("{label}: frozen state differs"));
                    }
                }
                "validate" => {
                    let value = parse_one(step["value"].as_str().unwrap(), "core");
                    let schema = parse_one(step["schema"].as_str().unwrap(), "core");
                    let report = validation_report2026_with(
                        &value,
                        &schema,
                        Some(&registry),
                        ValidationOptions::default(),
                    );
                    failures.extend(
                        report_differences(&report, &expected["report"])
                            .into_iter()
                            .map(|difference| format!("{label}: {difference}")),
                    );
                }
                other => panic!("unknown registry operation in fixture: {other}"),
            }
        }

        let final_state = &scenario["final"];
        if registry.len() != final_state["length"].as_u64().unwrap() as usize {
            failures.push(format!(
                "{scenario_id}: final length {}, expected {}",
                registry.len(),
                final_state["length"].as_u64().unwrap()
            ));
        }
        if registry.is_empty() != (final_state["length"].as_u64().unwrap() == 0) {
            failures.push(format!("{scenario_id}: is_empty differs from reference"));
        }
        if registry.frozen() != final_state["frozen"].as_bool().unwrap() {
            failures.push(format!("{scenario_id}: final frozen state differs"));
        }
        if registry.network_resolution() != final_state["network_resolution"].as_bool().unwrap() {
            failures.push(format!("{scenario_id}: network-resolution state differs"));
        }
        let got_items = canonical_modules(registry.items());
        let want_items = expected_modules(&final_state["items"]);
        if got_items != want_items {
            failures.push(format!(
                "{scenario_id}: final items {got_items:?}, expected {want_items:?}"
            ));
        }
        for (identifier, expected_schema) in &want_items {
            if !registry.contains(identifier) {
                failures.push(format!(
                    "{scenario_id}: contains returned false for {identifier:?}"
                ));
            }
            match registry.get(identifier) {
                Some(schema) if canonical(&schema) == *expected_schema => {}
                Some(schema) => failures.push(format!(
                    "{scenario_id}: get({identifier:?}) returned {:?}, expected {expected_schema:?}",
                    canonical(&schema)
                )),
                None => failures.push(format!(
                    "{scenario_id}: get({identifier:?}) returned None"
                )),
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} registry-scenario mismatch(es):\n{}",
        failures.len(),
        failures.join("\n")
    );
}
