/* Generated by Cython 3.2.8 */

#ifndef __PYX_HAVE__axon2___dumper
#define __PYX_HAVE__axon2___dumper

#include "Python.h"
struct SimpleDumpers;
struct Dumper;

/* "axon2/_dumper.pxd":154
 * cdef SimpleDumper _simple_dumper
 * 
 * cdef public class SimpleDumpers[type SimpleDumpersType, object SimpleDumpers]:             # <<<<<<<<<<<<<<
 *     cdef public dict mapping
 * 
*/
struct SimpleDumpers {
  PyObject_HEAD
  struct __pyx_vtabstruct_5axon2_7_dumper_SimpleDumpers *__pyx_vtab;
  PyObject *mapping;
};

/* "axon2/_dumper.pxd":181
 * #ctypedef unicode *SimpleDumperFunction(object)
 * 
 * @cython.final             # <<<<<<<<<<<<<<
 * cdef public class Dumper[object Dumper, type DumperType]:
 *     '''
*/
struct Dumper {
  PyObject_HEAD
  struct __pyx_vtabstruct_5axon2_7_dumper_Dumper *__pyx_vtab;
  PyObject *c_simple_dumpers;
  PyObject *c_type_reducers;
  int hsize;
  PyObject *fd;
  struct __pyx_obj_5axon2_8_objects_StringWriter *sfd;
  struct __pyx_obj_5axon2_7_dumper_SimpleDumper *sdumper;
  int pretty;
  int sorted;
  int crossref;
  PyObject *crossref_dict;
  PyObject *crossref_set;
  PyObject *crossref_set2;
  int collected;
  int c_depth;
  int c_max_depth;
};

#ifndef __PYX_HAVE_API__axon2___dumper

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) SimpleDumpersType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) DumperType;

__PYX_EXTERN_C PyObject *c_reduce_dict;
__PYX_EXTERN_C PyObject *__pyx_v_5axon2_7_dumper_c_all_names;
__PYX_EXTERN_C PyObject *__pyx_v_5axon2_7_dumper_c_factory_dict;
__PYX_EXTERN_C PyObject *__pyx_v_5axon2_7_dumper_c_simple_dumpers;

#endif /* !__PYX_HAVE_API__axon2___dumper */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("_dumper", PyInit__dumper) instead of calling PyInit__dumper directly from Python 3.5 */
PyMODINIT_FUNC PyInit__dumper(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"_dumper\", PyInit__dumper) instead of calling PyInit__dumper directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"_dumper\", PyInit__dumper) instead of calling PyInit__dumper directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"_dumper\", PyInit__dumper) instead of calling PyInit__dumper directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit__dumper_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit__dumper() __PYX_WARN_IF_PyInit__dumper_INIT_CALLED(PyInit__dumper())
#endif

#endif /* !__PYX_HAVE__axon2___dumper */
