/* Generated by Cython 3.2.8 */

#ifndef __PYX_HAVE__axon2___objects
#define __PYX_HAVE__axon2___objects

#include "Python.h"
struct UndefinedObject;
struct AttributeObject;
struct KeyValObject;
struct NodeObject;
struct SimpleBuilder;
struct TimeZoneUTCObject;

/* "axon2/_objects.pxd":153
 * # cdef Token tuple_token = c_new_token0(TUPLE)
 * 
 * @cython.final             # <<<<<<<<<<<<<<
 * cdef public class Undefined[object UndefinedObject, type UndefinedType]:
 *     pass
*/
struct UndefinedObject {
  PyObject_HEAD
};

/* "axon2/_objects.pxd":179
 * # Attribute
 * #
 * @cython.freelist(128)             # <<<<<<<<<<<<<<
 * @cython.final
 * cdef public class Attribute[type AttributeType, object AttributeObject]:
*/
struct AttributeObject {
  PyObject_HEAD
  PyObject *name;
  PyObject *val;
};

/* "axon2/_objects.pxd":193
 * # KeyVal
 * #
 * @cython.freelist(128)             # <<<<<<<<<<<<<<
 * @cython.final
 * cdef public class KeyVal[type KeyValType, object KeyValObject]:
*/
struct KeyValObject {
  PyObject_HEAD
  PyObject *key;
  PyObject *val;
};

/* "axon2/_objects.pxd":211
 * #
 * 
 * @cython.freelist(128)             # <<<<<<<<<<<<<<
 * @cython.final
 * cdef public class Node[type NodeType, object NodeObject]:
*/
struct NodeObject {
  PyObject_HEAD
  PyObject *name;
  struct OrderedDictObject *attrs;
  PyObject *vals;
};

/* "axon2/_objects.pxd":287
 * cdef dict tz_dict = {}
 * 
 * cdef public class SimpleBuilder[type SimpleBuilderType, object SimpleBuilder]:             # <<<<<<<<<<<<<<
 * 
 *     @cython.locals(n=int, i=int, buf=cython.p_char, num_buffer=bytes)
*/
struct SimpleBuilder {
  PyObject_HEAD
  struct __pyx_vtabstruct_5axon2_8_objects_SimpleBuilder *__pyx_vtab;
};

/* "axon2/_objects.pxd":339
 * cdef object timezone_cls
 * 
 * cdef public class timezone(tzinfo)[object TimeZoneUTCObject, type TimeZoneUTCType]:             # <<<<<<<<<<<<<<
 *     """Fixed offset in minutes east from UTC."""
 * 
*/
struct TimeZoneUTCObject {
  PyDateTime_TZInfo __pyx_base;
  PyObject *offset;
  PyObject *name;
};

#ifndef __PYX_HAVE_API__axon2___objects

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) UndefinedType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) AttributeType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) KeyValType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) NodeType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) SimpleBuilderType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) TimeZoneUTCType;

__PYX_EXTERN_C struct AttributeObject *c_new_attribute(PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *c_new_keyval(PyObject *, PyObject *);
__PYX_EXTERN_C PyObject *c_new_node(PyObject *, struct OrderedDictObject *, PyObject *);

__PYX_EXTERN_C PyObject *__pyx_v_5axon2_8_objects_empty_name;
__PYX_EXTERN_C PyObject *__pyx_v_5axon2_8_objects_c_undescore;
__PYX_EXTERN_C PyObject *__pyx_v_5axon2_8_objects_name_cache;
__PYX_EXTERN_C PyObject *__pyx_v_5axon2_8_objects_c_undefined;
__PYX_EXTERN_C PyObject *c_factory_dict;

#endif /* !__PYX_HAVE_API__axon2___objects */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("_objects", PyInit__objects) instead of calling PyInit__objects directly from Python 3.5 */
PyMODINIT_FUNC PyInit__objects(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"_objects\", PyInit__objects) instead of calling PyInit__objects directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"_objects\", PyInit__objects) instead of calling PyInit__objects directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"_objects\", PyInit__objects) instead of calling PyInit__objects directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit__objects_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit__objects() __PYX_WARN_IF_PyInit__objects_INIT_CALLED(PyInit__objects())
#endif

#endif /* !__PYX_HAVE__axon2___objects */
