/* Generated by Cython 3.2.8 */

#ifndef __PYX_HAVE__axon2__odict
#define __PYX_HAVE__axon2__odict

#include "Python.h"
struct LinkObject;
struct OrderedDictObject;

/* "axon2/odict.pxd":60
 * ################################################################################
 * 
 * @cython.freelist(64)             # <<<<<<<<<<<<<<
 * @cython.final
 * cdef public class Link[object LinkObject, type LinkType]:
*/
struct LinkObject {
  PyObject_HEAD
  void *prev;
  void *next;
  PyObject *key;
  PyObject *val;
};

/* "axon2/odict.pxd":70
 * cdef Link link_marker
 * 
 * cdef public class OrderedDict[object OrderedDictObject, type OrderedDictType]:             # <<<<<<<<<<<<<<
 *     cdef Link root
 *     cdef dict map
*/
struct OrderedDictObject {
  PyObject_HEAD
  struct __pyx_vtabstruct_5axon2_5odict_OrderedDict *__pyx_vtab;
  struct LinkObject *root;
  PyObject *map;
};

#ifndef __PYX_HAVE_API__axon2__odict

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) LinkType;
__PYX_EXTERN_C DL_IMPORT(PyTypeObject) OrderedDictType;

#endif /* !__PYX_HAVE_API__axon2__odict */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("odict", PyInit_odict) instead of calling PyInit_odict directly from Python 3.5 */
PyMODINIT_FUNC PyInit_odict(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"odict\", PyInit_odict) instead of calling PyInit_odict directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"odict\", PyInit_odict) instead of calling PyInit_odict directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"odict\", PyInit_odict) instead of calling PyInit_odict directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_odict_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_odict() __PYX_WARN_IF_PyInit_odict_INIT_CALLED(PyInit_odict())
#endif

#endif /* !__PYX_HAVE__axon2__odict */
